services:
  - type: web
    name: sistema-contratacoes-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sistema-contratacoes-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production

  - type: postgres
    name: sistema-contratacoes-db
    databaseName: contratos_db
    user: contratos_user