"""remove_atrasada_vencida_fields

Revision ID: 0d9e636089c7
Revises: 98ce7061a9d7
Create Date: 2025-09-18 14:06:46.957020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9e636089c7'
down_revision = '98ce7061a9d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pca', 'vencida')
    op.drop_column('pca', 'atrasada')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pca', sa.Column('atrasada', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('pca', sa.Column('vencida', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###