"""add economia field to licitacao

Revision ID: 0eab458e2d03
Revises: 0d9e636089c7
Create Date: 2025-09-23 15:09:42.922970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eab458e2d03'
down_revision = '0d9e636089c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###