"""Fix relationships

Revision ID: 29888ea16897
Revises: e2088ac6a5d5
Create Date: 2025-09-10 15:29:57.982853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29888ea16897'
down_revision = 'e2088ac6a5d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###