"""add_ano_field_to_tables

Revision ID: 61261242b3db
Revises: 0eab458e2d03
Create Date: 2025-09-24 11:45:19.326142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61261242b3db'
down_revision = '0eab458e2d03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Add nullable columns with default values
    op.add_column('licitacoes', sa.Column('ano', sa.Integer(), nullable=True, server_default='2025'))
    op.add_column('pca', sa.Column('ano_pca', sa.Integer(), nullable=True, server_default='2025'))
    op.add_column('qualificacoes', sa.Column('ano', sa.Integer(), nullable=True, server_default='2025'))

    # Step 2: Update all existing records to have the default year
    op.execute("UPDATE licitacoes SET ano = 2025 WHERE ano IS NULL")
    op.execute("UPDATE pca SET ano_pca = 2025 WHERE ano_pca IS NULL")
    op.execute("UPDATE qualificacoes SET ano = 2025 WHERE ano IS NULL")

    # Step 3: Make columns NOT NULL and remove server default
    op.alter_column('licitacoes', 'ano', nullable=False, server_default=None)
    op.alter_column('pca', 'ano_pca', nullable=False, server_default=None)
    op.alter_column('qualificacoes', 'ano', nullable=False, server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qualificacoes', 'ano')
    op.drop_constraint('unique_contratacao_ano', 'pca', type_='unique')
    op.drop_index(op.f('ix_pca_numero_contratacao'), table_name='pca')
    op.create_index(op.f('ix_pca_numero_contratacao'), 'pca', ['numero_contratacao'], unique=True)
    op.drop_column('pca', 'ano_pca')
    op.drop_column('licitacoes', 'ano')
    # ### end Alembic commands ###