"""add vencida field to pca

Revision ID: 98ce7061a9d7
Revises: f231055befc0
Create Date: 2025-09-16 14:01:08.560572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ce7061a9d7'
down_revision = 'f231055befc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pca', sa.Column('vencida', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pca', 'vencida')
    # ### end Alembic commands ###