"""add access_requests table

Revision ID: e0b8a4e563ad
Revises: 037613cbe1ac
Create Date: 2025-09-24 19:46:55.468178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b8a4e563ad'
down_revision = '037613cbe1ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nivel_solicitado', sa.String(), nullable=False),
    sa.Column('trabalha_cglic', sa.Boolean(), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('observacoes_admin', sa.Text(), nullable=True),
    sa.Column('aprovado_por_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aprovado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_requests')
    # ### end Alembic commands ###