"""Initial migration

Revision ID: e2088ac6a5d5
Revises: 
Create Date: 2025-09-10 15:28:13.781475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2088ac6a5d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nivel_acesso', sa.Enum('COORDENADOR', 'DIPLAN', 'DIQUALI', 'DIPLI', 'VISITANTE', name='nivelacesso'), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('pca',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero_contratacao', sa.String(length=50), nullable=False),
    sa.Column('status_contratacao', sa.String(length=100), nullable=True),
    sa.Column('situacao_execucao', sa.String(length=100), nullable=True),
    sa.Column('titulo_contratacao', sa.Text(), nullable=True),
    sa.Column('categoria_contratacao', sa.String(length=100), nullable=True),
    sa.Column('valor_total', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('area_requisitante', sa.String(length=200), nullable=True),
    sa.Column('numero_dfd', sa.String(length=50), nullable=True),
    sa.Column('data_estimada_inicio', sa.Date(), nullable=True),
    sa.Column('data_estimada_conclusao', sa.Date(), nullable=True),
    sa.Column('atrasada', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pca_numero_contratacao'), 'pca', ['numero_contratacao'], unique=True)
    op.create_table('qualificacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nup', sa.String(length=50), nullable=False),
    sa.Column('numero_contratacao', sa.String(length=50), nullable=False),
    sa.Column('area_demandante', sa.String(length=200), nullable=True),
    sa.Column('responsavel_instrucao', sa.String(length=200), nullable=True),
    sa.Column('modalidade', sa.String(length=100), nullable=True),
    sa.Column('objeto', sa.Text(), nullable=True),
    sa.Column('palavra_chave', sa.String(length=200), nullable=True),
    sa.Column('valor_estimado', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.Enum('EM_ANALISE', 'CONCLUIDO', name='statusqualificacao'), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['numero_contratacao'], ['pca.numero_contratacao'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualificacoes_nup'), 'qualificacoes', ['nup'], unique=True)
    op.create_table('licitacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nup', sa.String(length=50), nullable=False),
    sa.Column('numero_contratacao', sa.String(length=50), nullable=True),
    sa.Column('area_demandante', sa.String(length=200), nullable=True),
    sa.Column('responsavel_instrucao', sa.String(length=200), nullable=True),
    sa.Column('modalidade', sa.String(length=100), nullable=True),
    sa.Column('objeto', sa.Text(), nullable=True),
    sa.Column('palavra_chave', sa.String(length=200), nullable=True),
    sa.Column('valor_estimado', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('pregoeiro', sa.String(length=200), nullable=True),
    sa.Column('valor_homologado', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('data_homologacao', sa.Date(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('HOMOLOGADA', 'FRACASSADA', 'EM_ANDAMENTO', 'REVOGADA', name='statuslicitacao'), nullable=True),
    sa.Column('economia', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['nup'], ['qualificacoes.nup'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('licitacoes')
    op.drop_index(op.f('ix_qualificacoes_nup'), table_name='qualificacoes')
    op.drop_table('qualificacoes')
    op.drop_index(op.f('ix_pca_numero_contratacao'), table_name='pca')
    op.drop_table('pca')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###