"""Make numero_contratacao nullable in qualificacoes

Revision ID: e638db3da5f9
Revises: 29888ea16897
Create Date: 2025-09-15 13:13:34.128344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e638db3da5f9'
down_revision = '29888ea16897'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qualificacoes', 'numero_contratacao',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(op.f('qualificacoes_numero_contratacao_fkey'), 'qualificacoes', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('qualificacoes_numero_contratacao_fkey'), 'qualificacoes', 'pca', ['numero_contratacao'], ['numero_contratacao'])
    op.alter_column('qualificacoes', 'numero_contratacao',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###