"""Restore numero_contratacao foreign key

Revision ID: f231055befc0
Revises: e638db3da5f9
Create Date: 2025-09-15 13:15:40.088708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f231055befc0'
down_revision = 'e638db3da5f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qualificacoes', 'numero_contratacao',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_foreign_key(None, 'qualificacoes', 'pca', ['numero_contratacao'], ['numero_contratacao'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'qualificacoes', type_='foreignkey')
    op.alter_column('qualificacoes', 'numero_contratacao',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###